export enum AuthActionTypes {
  DELETE_SELF = 'DELETE_SELF',
  UPDATE_SELF = 'UPDATE_SELF',
  SHOW_SELF = 'SHOW_SELF',
  NEW_SUBUSER = 'NEW_SUBUSER',
  INDEX_SUBUSER = 'INDEX_SUBUSER',
  DELETE_USER = 'DELETE_USER',
  SHOW_USER = 'SHOW_USER',
  UPDATE_USER = 'UPDATE_USER',
  CREATE_USER = 'CREATE_USER',
  INDEX_USER = 'INDEX_USER'
};