export enum ProfileActionTypes {
  DELETE_PROFILE = 'DELETE_PROFILE',
  UPDATE_PROFILE = 'UPDATE_PROFILE',
  SHOW_PROFILE = 'SHOW_PROFILE',
  NEW_PROFILE = 'NEW_PROFILE',
  INDEX_PROFILE = 'INDEX_PROFILE',
};